### ISSUE TITLE
Broken on native targets

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/away3d#2]
Current version of the library is broken on windows target, as of openfl 4.6.0!

```
Error: RegisterPool.cpp
./src/away3d/materials/compilation/RegisterPool.cpp(146): error C2374: 'index1': redefinition; multiple initialization
./src/away3d/materials/compilation/RegisterPool.cpp(144): note: see declaration of 'index1'
./src/away3d/materials/compilation/RegisterPool.cpp(147): error C2228: left of '.StaticCast' must have class/struct/union
./src/away3d/materials/compilation/RegisterPool.cpp(147): error C2059: syntax error: ')'
./src/away3d/materials/compilation/RegisterPool.cpp(173): error C2374: 'index1': redefinition; multiple initialization
./src/away3d/materials/compilation/RegisterPool.cpp(171): note: see declaration of 'index1'
./src/away3d/materials/compilation/RegisterPool.cpp(174): error C2228: left of '.StaticCast' must have class/struct/union
./src/away3d/materials/compilation/RegisterPool.cpp(174): error C2059: syntax error: ')'
```

(hoping it's an easy fix!)

**Comment by Gama11** [comment]
This appears to be a Haxe / Cpp regression. I can reproduce this error with Haxe 3.4.0-rc.2 and latest hxcpp, but `RegisterPool` compiles fine using Haxe 3.2.1 and Hxcpp 3.2.205.

**Comment by Gama11** [comment]
I've isolated and reported it: https://github.com/HaxeFoundation/haxe/issues/5957

**Comment by TerryCavanagh** [comment]
Oh, nice! Thanks!

**Comment by Gama11** [comment]
The corresponding Haxe issue has been fixed, so I guess this can be closed.

**Comment by TerryCavanagh** [comment]
Great! Looking forward to the next haxe release!
